---
title: "Using R to Create Website"
date: "2022-05-29"
urlcolor: blue
output: pdf_document
---

I have been using R for over four years. In the beginning, I did not think to create a website with R, but people should know that R is more than a statistical language and you can become addicted to R in a short time. :smile: In this blog, I will provide some books, links, and videos that may be beneficial for people who want to create website by using R markdown. 

First of all, R markdown documents provide an opportunity to create quick, efficient, and reproducible documents by using R. You can produce MS Word, PDF or HTML output with R markdown. For more information, check out these websites and books. 

- [**Introduction to R Markdown**](https://rmarkdown.rstudio.com/articles_intro.html)
- [**R Markdown Cookbook**](https://bookdown.org/yihui/rmarkdown-cookbook/)

If you are familiar with R markdown, focus on the blogdown package that helps to create static websites. To install the blogdown, use the following code:

```{r echo=TRUE, results='hide'}
install.packages("blogdown", repos = "http://cran.us.r-project.org")

library(blogdown)
```

After installing the package, look into these links that are perfect for the blogdown users who are beginners and intermediate level R user. 

- [**Introduction to Blogdown - (Video link)**](https://www.youtube.com/watch?v=CjTLN-FXiFA)
- [**blogdown: Creating Websites with R Markdown**](https://bookdown.org/yihui/blogdown/)

Becoming an advanced user might take time in R markdown and blogdown. But this is not an obstacle for you to create a website with the blogdown. Some R users and theme developers have amazing tutorials that explain every single step before publishing your website. For me, [Alison Hill](https://www.apreshill.com/)’s amazing recordings have helped me to develop my personal website. I recommend watching her videos on [YouTube](https://www.youtube.com/channel/UCQYM-t2ut2zXr4d7TIFya1A). This [video](https://www.youtube.com/watch?v=AADnslLpzJ4) in particular is the most helpful for beginners because it demonstrates the process of building a website from start to finish. 

In this blog, I have provided several links, books, and videos but this will not be the last post. I am planning to record a video that explains how to create a website by using R for beginners. See you soon! :wave:  




